apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/rds.services.k8s.aws_dbparametergroups.yaml
  - bases/rds.services.k8s.aws_dbsecuritygroups.yaml
  - bases/rds.services.k8s.aws_dbsubnetgroups.yaml
